version: "3.9"

services:
  database:
    image: postgres
    container_name: ecommerce_database
    restart: always
    ports:
      - 65432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=e796edee-ad0d-42a4-8257-b0fab35b37ee
      - POSTGRES_DB=success_ecommerce
    volumes:
      - pagedata:/data/postgres

  app:
    build: .
    container_name: ecommerce_backend
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
